2025-05-08 16:45:55,138 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164555-51nmbe36/logs/debug.log
2025-05-08 16:45:55,138 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164555-51nmbe36/logs/debug-internal.log
2025-05-08 16:45:55,139 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:45:55,139 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:45:55,139 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:45:55,139 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:45:55,143 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:45:55,144 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:45:55,145 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:45:55,146 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:45:55,176 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:46:04,570 WARNING MainThread:59405 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-05-08 16:46:16,651 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164616-4t691f5f/logs/debug.log
2025-05-08 16:46:16,651 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164616-4t691f5f/logs/debug-internal.log
2025-05-08 16:46:16,652 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:46:16,652 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:46:16,652 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:46:16,652 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:46:16,657 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:46:16,657 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:46:16,659 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:46:16,659 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:46:16,689 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:47:28,105 WARNING MainThread:59405 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-05-08 16:47:43,666 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164743-8krcquxo/logs/debug.log
2025-05-08 16:47:43,668 INFO    MainThread:59405 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_164743-8krcquxo/logs/debug-internal.log
2025-05-08 16:47:43,669 INFO    MainThread:59405 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:47:43,669 INFO    MainThread:59405 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:47:43,669 INFO    MainThread:59405 [wandb_init.py:init():789] starting backend
2025-05-08 16:47:43,669 INFO    MainThread:59405 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:47:43,674 INFO    MainThread:59405 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:47:43,675 INFO    MainThread:59405 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:47:43,676 INFO    MainThread:59405 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:47:43,677 INFO    MainThread:59405 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:47:43,706 INFO    MainThread:59405 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:48:09,489 WARNING MainThread:59405 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
